package corba.Arith;


/**
* Arith/_MultiplicationStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from communication/src/main/resources/corba/Arith.idl
* Thursday, May 26, 2016 11:01:55 PM CEST
*/

public class _MultiplicationStub extends org.omg.CORBA.portable.ObjectImpl implements Multiplication
{

  public void mulitply (double x, double y, org.omg.CORBA.DoubleHolder result)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("mulitply", true);
                $out.write_double (x);
                $out.write_double (y);
                $in = _invoke ($out);
                result.value = $in.read_double ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                mulitply (x, y, result        );
            } finally {
                _releaseReply ($in);
            }
  } // mulitply

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Arith/Multiplication:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _MultiplicationStub
