package corba.Arith;


/**
* Arith/MultiplicationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from communication/src/main/resources/corba/Arith.idl
* Thursday, May 26, 2016 11:01:55 PM CEST
*/

public interface MultiplicationOperations 
{
  void mulitply (double x, double y, org.omg.CORBA.DoubleHolder result);
} // interface MultiplicationOperations
