package corba.Arith;

/**
* Arith/MultiplicationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from communication/src/main/resources/corba/Arith.idl
* Thursday, May 26, 2016 11:01:55 PM CEST
*/

public final class MultiplicationHolder implements org.omg.CORBA.portable.Streamable
{
  public Multiplication value = null;

  public MultiplicationHolder ()
  {
  }

  public MultiplicationHolder (Multiplication initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MultiplicationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MultiplicationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MultiplicationHelper.type ();
  }

}
