package corba.Arith;


/**
* Arith/Multiplication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from communication/src/main/resources/corba/Arith.idl
* Thursday, May 26, 2016 11:01:55 PM CEST
*/

public interface Multiplication extends MultiplicationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Multiplication
