package corba.Arith;


/**
* Arith/MultiplicationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from communication/src/main/resources/corba/Arith.idl
* Thursday, May 26, 2016 11:01:55 PM CEST
*/

abstract public class MultiplicationHelper
{
  private static String  _id = "IDL:Arith/Multiplication:1.0";

  public static void insert (org.omg.CORBA.Any a, Multiplication that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Multiplication extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MultiplicationHelper.id (), "Multiplication");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Multiplication read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MultiplicationStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Multiplication value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Multiplication narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Multiplication)
      return (Multiplication)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _MultiplicationStub stub = new _MultiplicationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Multiplication unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Multiplication)
      return (Multiplication)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _MultiplicationStub stub = new _MultiplicationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
